### ISSUE TITLE
Load all users in a more efficient way

### ISSUE THREAD

**Issue by kkneomis** [KC7-Foundation/kc7_scoreboard#22]
On the `Admins > Manage Users` page, all the users are queried from the database and rendered in the view via jinja. 

With 700+ users, it makes the page very slow to load. Can we make users searchable instead? and/or load them all via javascript to make the page more efficient?

**Comment by Boorclark** [comment]
### Notes

- JSON → Send user data as a JSON via Ajax?
- Here is an Ajax refresher: https://www.geeksforgeeks.org/how-to-make-ajax-call-from-javascript/
