### ISSUE TITLE
Malformed div on Manager sessions page. 

### ISSUE THREAD

**Issue by kkneomis** [KC7-Foundation/kc7_scoreboard#23]
The table on the manage sessions page appears to leak past its container. Can we figure out how to fix this?

It might be wise to remove the "end time" column as well!

**Comment by Boorclark** [comment]
I am assuming you have already addressed this but I thought I would make sure. I do not see any leaking or an "end time" column.
![image](https://user-images.githubusercontent.com/97637517/236693724-613dcdd1-c440-448e-91df-282e315a5cfd.png)

**Comment by kkneomis** [comment]
@Boorclark yup, his has already been addressed

**Comment by Boorclark** [comment]
Closing issue.
